/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Ejercicio1': RouteRecordInfo<'/Ejercicio1', '/Ejercicio1', Record<never, never>, Record<never, never>>,
    '/Ejercicio2': RouteRecordInfo<'/Ejercicio2', '/Ejercicio2', Record<never, never>, Record<never, never>>,
    '/Ejercicio3': RouteRecordInfo<'/Ejercicio3', '/Ejercicio3', Record<never, never>, Record<never, never>>,
    '/Ejercicio4': RouteRecordInfo<'/Ejercicio4', '/Ejercicio4', Record<never, never>, Record<never, never>>,
    '/Ejercicio5': RouteRecordInfo<'/Ejercicio5', '/Ejercicio5', Record<never, never>, Record<never, never>>,
    '/Formulario': RouteRecordInfo<'/Formulario', '/Formulario', Record<never, never>, Record<never, never>>,
    '/Transitions': RouteRecordInfo<'/Transitions', '/Transitions', Record<never, never>, Record<never, never>>,
  }
}
